server:
  port: 8080
  host: "0.0.0.0"

# LLM конфигурация
ai:
  provider: "openrouter"
  apiKey: "${OPENAI_API_KEY}"
  model: "meta-llama/llama-3.1-8b-instruct"

# Telegram конфигурация
telegram:
  defaultUserId: "${TELEGRAM_CHAT_ID}"

